import { create } from 'zustand';

export type Lang = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'pt' | 'ru' | 'ja' | 'zh' | 'ar';

type Dictionary = Record<string, string>;

const translations: Record<Lang, Dictionary> = {
  en: { appTitle:'Cartify', products:'Products', cart:'Cart', login:'Login', signup:'Sign up', logout:'Logout', searchPlaceholder:'Search…', minPrice:'Min price', maxPrice:'Max price', allCategories:'All categories', filter:'Filter', addToCart:'Add to cart', yourCartEmpty:'Your cart is empty.', orderSummary:'Order Summary', subtotal:'Subtotal', checkout:'Checkout', welcomeBack:'Welcome back', signIn:'Sign in', creating:'Creating…', createAccount:'Create account', name:'Name', email:'Email', password:'Password' },
  hi: { appTitle:'Cartify', products:'उत्पाद', cart:'कार्ट', login:'लॉगिन', signup:'साइन अप', logout:'लॉगआउट', searchPlaceholder:'खोजें…', minPrice:'न्यूनतम कीमत', maxPrice:'अधिकतम कीमत', allCategories:'सभी श्रेणियाँ', filter:'फिल्टर', addToCart:'कार्ट में जोड़ें', yourCartEmpty:'आपका कार्ट खाली है।', orderSummary:'ऑर्डर सारांश', subtotal:'उप-कुल', checkout:'भुगतान', welcomeBack:'फिर से स्वागत है', signIn:'साइन इन', creating:'बना रहे हैं…', createAccount:'खाता बनाएं', name:'नाम', email:'ईमेल', password:'पासवर्ड' },
  es: { appTitle:'Cartify', products:'Productos', cart:'Carrito', login:'Iniciar sesión', signup:'Registrarse', logout:'Cerrar sesión', searchPlaceholder:'Buscar…', minPrice:'Precio mínimo', maxPrice:'Precio máximo', allCategories:'Todas las categorías', filter:'Filtrar', addToCart:'Añadir al carrito', yourCartEmpty:'Tu carrito está vacío.', orderSummary:'Resumen de pedido', subtotal:'Subtotal', checkout:'Pagar', welcomeBack:'Bienvenido de nuevo', signIn:'Iniciar sesión', creating:'Creando…', createAccount:'Crear cuenta', name:'Nombre', email:'Correo', password:'Contraseña' },
  fr: { appTitle:'Cartify', products:'Produits', cart:'Panier', login:'Connexion', signup:'Inscription', logout:'Déconnexion', searchPlaceholder:'Rechercher…', minPrice:'Prix min', maxPrice:'Prix max', allCategories:'Toutes les catégories', filter:'Filtrer', addToCart:'Ajouter au panier', yourCartEmpty:'Votre panier est vide.', orderSummary:'Récapitulatif', subtotal:'Sous-total', checkout:'Payer', welcomeBack:'Bon retour', signIn:'Se connecter', creating:'Création…', createAccount:'Créer un compte', name:'Nom', email:'E-mail', password:'Mot de passe' },
  de: { appTitle:'Cartify', products:'Produkte', cart:'Warenkorb', login:'Anmelden', signup:'Registrieren', logout:'Abmelden', searchPlaceholder:'Suchen…', minPrice:'Mindestpreis', maxPrice:'Höchstpreis', allCategories:'Alle Kategorien', filter:'Filtern', addToCart:'In den Warenkorb', yourCartEmpty:'Dein Warenkorb ist leer.', orderSummary:'Bestellübersicht', subtotal:'Zwischensumme', checkout:'Zur Kasse', welcomeBack:'Willkommen zurück', signIn:'Anmelden', creating:'Erstellen…', createAccount:'Konto erstellen', name:'Name', email:'E-Mail', password:'Passwort' },
  pt: { appTitle:'Cartify', products:'Produtos', cart:'Carrinho', login:'Entrar', signup:'Cadastrar', logout:'Sair', searchPlaceholder:'Buscar…', minPrice:'Preço mín', maxPrice:'Preço máx', allCategories:'Todas as categorias', filter:'Filtrar', addToCart:'Adicionar ao carrinho', yourCartEmpty:'Seu carrinho está vazio.', orderSummary:'Resumo do pedido', subtotal:'Subtotal', checkout:'Finalizar', welcomeBack:'Bem-vindo de volta', signIn:'Entrar', creating:'Criando…', createAccount:'Criar conta', name:'Nome', email:'E-mail', password:'Senha' },
  ru: { appTitle:'Cartify', products:'Товары', cart:'Корзина', login:'Войти', signup:'Регистрация', logout:'Выйти', searchPlaceholder:'Поиск…', minPrice:'Мин. цена', maxPrice:'Макс. цена', allCategories:'Все категории', filter:'Фильтр', addToCart:'В корзину', yourCartEmpty:'Ваша корзина пуста.', orderSummary:'Сводка заказа', subtotal:'Промежуточный итог', checkout:'Оформить', welcomeBack:'С возвращением', signIn:'Войти', creating:'Создание…', createAccount:'Создать аккаунт', name:'Имя', email:'Email', password:'Пароль' },
  ja: { appTitle:'Cartify', products:'商品', cart:'カート', login:'ログイン', signup:'登録', logout:'ログアウト', searchPlaceholder:'検索…', minPrice:'最小価格', maxPrice:'最大価格', allCategories:'すべてのカテゴリ', filter:'絞り込み', addToCart:'カートに追加', yourCartEmpty:'カートは空です。', orderSummary:'注文概要', subtotal:'小計', checkout:'購入手続き', welcomeBack:'おかえりなさい', signIn:'ログイン', creating:'作成中…', createAccount:'アカウント作成', name:'名前', email:'メール', password:'パスワード' },
  zh: { appTitle:'Cartify', products:'商品', cart:'购物车', login:'登录', signup:'注册', logout:'退出', searchPlaceholder:'搜索…', minPrice:'最低价格', maxPrice:'最高价格', allCategories:'所有类别', filter:'筛选', addToCart:'加入购物车', yourCartEmpty:'你的购物车是空的。', orderSummary:'订单摘要', subtotal:'小计', checkout:'结账', welcomeBack:'欢迎回来', signIn:'登录', creating:'创建中…', createAccount:'创建账户', name:'姓名', email:'邮箱', password:'密码' },
  ar: { appTitle:'Cartify', products:'المنتجات', cart:'السلة', login:'تسجيل الدخول', signup:'إنشاء حساب', logout:'تسجيل الخروج', searchPlaceholder:'ابحث…', minPrice:'أدنى سعر', maxPrice:'أقصى سعر', allCategories:'كل الفئات', filter:'تصفية', addToCart:'أضف للسلة', yourCartEmpty:'سلتك فارغة.', orderSummary:'ملخص الطلب', subtotal:'المجموع الفرعي', checkout:'الدفع', welcomeBack:'مرحباً بعودتك', signIn:'تسجيل الدخول', creating:'جارٍ الإنشاء…', createAccount:'إنشاء حساب', name:'الاسم', email:'البريد الإلكتروني', password:'كلمة المرور' }
};

type I18nState = { lang: Lang; setLang: (lang: Lang) => void; t: (key: string) => string };

export const useI18n = create<I18nState>((set, get) => ({
  lang: (localStorage.getItem('cartify_lang') as Lang) || 'en',
  setLang: (lang) => { localStorage.setItem('cartify_lang', lang); set({ lang }); },
  t: (key) => { const { lang } = get(); return translations[lang]?.[key] ?? translations.en[key] ?? key; }
}));


